### ISSUE TITLE
Implement Core Login UI Components with Frosted Glass Design

### ISSUE THREAD

**Issue by firdausahmed40** [firdausahmed40/GoldenMed#1]
Create the core login interface components with frosted glass black/gold design.

#### 1. login.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Golden MedAI Login</title>
  <link rel="stylesheet" href="login.css">
</head>
<body>
  <div class="login-container">
    <div class="login-box">
      <input type="email" id="emailInput" placeholder="Enter your email" />
      <button onclick="checkAccess()">Unlock Your Potential</button>
    </div>
  </div>
  <script src="login.js"></script>
</body>
</html>
```

#### 2. login.css
```css
body, html {
  margin: 0;
  padding: 0;
  height: 100%;
  background: #000;
  font-family: 'Segoe UI', sans-serif;
}

.login-container {
  height: 100%;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  backdrop-filter: blur(12px);
  background: rgba(0, 0, 0, 0.6);
}

.login-box {
  background: rgba(255, 255, 255, 0.05);
  padding: 40px;
  border-radius: 16px;
  box-shadow: 0 0 30px rgba(255, 215, 0, 0.3);
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 20px;
}

input {
  padding: 14px 20px;
  font-size: 16px;
  width: 300px;
  background: rgba(0,0,0,0.3);
  border: 2px solid gold;
  border-radius: 8px;
  color: white;
  outline: none;
}

button {
  padding: 14px 30px;
  font-size: 16px;
  background: rgba(255, 255, 255, 0.1);
  border: 2px solid #fff;
  border-radius: 10px;
  color: #fff;
  cursor: pointer;
  backdrop-filter: blur(10px);
  box-shadow: 0 0 12px #ffdf00;
  transition: 0.3s;
}

button:hover {
  background: rgba(255, 255, 255, 0.2);
}
```

### Requirements

- [x] Full-screen jet black background
- [x] Frosted glass effect on container
- [x] Centered login box with glass morphism
- [x] Single email input with golden glowing border
- [x] "Unlock Your Potential" button with hover effects
- [x] Mobile responsive design
- [x] Smooth animations and transitions

### Testing Checklist
1. Verify frosted glass effect works across browsers
2. Test responsiveness on mobile devices
3. Confirm golden glow effects are visible
4. Check input field focus states
5. Verify button hover animations
